config/routes.rb
Rails.application.routes.draw do
  resources :leaderboards
  resources :activities
  resources :players
  resources :messages
  resources :sessions
  
  get 'login', to: "sessions#new", as: "login"
  get 'logout', to: "sessions#destroy", as: "logout"
  
  root 'messages#index'
 
  
  namespace :api do
	resources :messages
	resources :players
	resources :activities
	resources :leaderboards
  end

end

app/models/activity.rb
class Activity < ActiveRecord::Base
	validates :level, :inclusion => { :in => ["Easy","Medium","Hard"]}
end

app/models/leaderboard.rb
class Leaderboard < ActiveRecord::Base
	validates :name, presence: true
	validates :level, :inclusion => { :in => ["Easy","Medium","Hard"]}
	validates :score, presence: true
	
	def as_json(options={})
		super(only: [:name,:score,:rank])
	end
	
end

app/models/message.rb
class Message < ActiveRecord::Base
	validates :usage, :inclusion => { :in => ["Win","Lose"]}
	
	#06.06.2016: overrides the as_json method to only display the usage and body in the API
	def as_json(options={})
		super(only: [:usage,:body])
	end
	
end

app/models/player.rb
class Player < ActiveRecord::Base
	#24.06.2016: validates that the player has a name, and that this name does not already exist
	validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base

# 30.07.2016: added the sign up validation and the api token generation
has_secure_password
validates :email, presence: true, uniqueness: true
validates :api_token, presence: true, uniqueness: true
before_validation :generate_api_token

def generate_api_token
	return if api_token.present?
	
	loop do
		self.api_token=SecureRandom.hex
		break unless User.exists? api_token: api_token
	end
end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
end

app/controllers/api/activities_controller.rb
module Api
	class ActivitiesController < ApplicationController
		before_action :authenticate_token!
		
		respond_to :json
		
		def index
			@activity=Activity.all
			respond_with @activity
		end
	
		def create
			@activity = Activity.new(activity_params)
			@activity.save
			respond_with @activity 
			
		end	
		
		private
		
		def activity_params
			params.require(:activity).permit(:name,:level)
		end
		
	end
end

app/controllers/api/leaderboards_controller.rb
module Api
	class LeaderboardsController < ApplicationController
		before_action :authenticate_token!
		
		respond_to :json
		
		def index
			#List of scores corresponding to the level required
			@table=Leaderboard.where("level = ?",params[:level])
			#List of the ten best scores on the level
			@a=@table.order(:score).first(10)
			#Best score of the user on the level
			@b=@table.where("name = ?",params[:name]).order(:score).first
			#Concatenation
			if !@b.nil? and !@a.to_s.include?(params[:name])
					@a.append(@b)
			end
			#Addition of the rank
			@a.each do |x|
					x.assign_attributes(rank: @table.where("score < ?",x.score).count + 1)
			end
			respond_with @a
		end
	
		def create
			@leaderboard = Leaderboard.new(leaderboard_params)
			@leaderboard.save
			respond_with @leaderboard 
		end	
		
		private
		
		def leaderboard_params
			params.require(:leaderboard).permit(:name,:level,:score)
		end
		

	end
end

app/controllers/api/messages_controller.rb
module Api
	class MessagesController < ApplicationController
		#15.08.2016: added the authentication before the action
		before_action :authenticate_token!
		
		respond_to :json
		
		def index
			@messages = Message.all
			respond_with @messages
		end
		
	end
end

app/controllers/api/players_controller.rb
module Api
	class PlayersController < ApplicationController
		#30.07.2016: added the token authentication
		before_action :authenticate_token!
		
		respond_to :json
		
		def index
			@player=Player.all
			respond_with @player
		end
	
		def create
			@player = Player.new(player_params)
			@player.save
			respond_with @player 
			
		end	
		
		private
		
		def player_params
			params.require(:player).permit(:name)
		end
		
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #30.07.2016: changed exception to null_session
  protect_from_forgery with: :null_session

#30.07.2016: added the authentication of the current user

private

def current_user
	if session[:user_id]
		@current_user ||= User.find(session[:user_id])
	end
end

helper_method :current_user

def authenticate_user!
	redirect_to login_path unless current_user
end

#30.07.2016: added the token-based authentication
def authenticate_token!
	authenticate_or_request_with_http_token do |token, options|
		@api_user = User.find_by(api_token: token)
	end
end


end

app/controllers/leaderboards_controller.rb
class LeaderboardsController < ApplicationController
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  # 24.07.2016: modified the show statement
  def show
	@message = Message.find(params[:id])
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:usage, :body)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

	def index
		@players = Player.all
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


#30.07.2016: added new, create, destroy

def new

end

def create
	user = User.find_by(email: params[:email])
	if user && user.authenticate(params[:password])
		session[:user_id] = user.id
		redirect_to root_url, notice: "Log in successful!"
	else
		flash.now.alert = "Invalid email or password"
	render "new"
	end
end

def destroy
	session[:user_id] = nil
	redirect_to root_url, notice: "Log out successful!"
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

#30.07.2016: added new, create and private user_params

def new
	@user=User.new
end

def create
	@user=User.new(user_params)
	if @user.save
		redirect_to root_url,
		notice: "Welcome to the great minesweeper!"
	else
		render "new"
	end
end


private

def user_params
	params_require(:user).permit(:name,:email,:password,:password_confirmation)
end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leaderboards_helper.rb
module LeaderboardsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :usage %><br>
    <%= f.text_field :usage %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
	<h1>Listing Messages</h1>
	<h2>The great messages of The Great Minesweeper!</h2>
</div>
<br>

<table border=4 cellspacing=3 cellpadding=20>
  <thead>
    <tr>
      <th>Usage</th>
      <th>Body</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.usage %></td>
        <td><%= message.body %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= button_to 'Destroy', {action: :destroy, id: message.id}, method: :delete, data: {confirm: "Are you sure?"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usage:</strong>
  <%= @message.usage %>
</p>

<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Players</h1>

<table>
  <thead>
    <tr>
	  <th>ID</th>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
		<td><%= player.id %></td>  
        <td><%= player.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>

app/views/users/new.html.erb
<div class="page-header">
	<h1>Sign Up</h1>
</div>

<%= form_for(@user) do |f| %>
	<% if @user.errors.any? %>
		<div class="alert alert-danger">
			<strong>
				<%= pluralize(@user.errors.count, "error") %>
				prevented you from signing up:
			</strong>
			<ul>
				<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
<% end %>

<div class="form-group">
	<%= f.label :email %>
	<%= f.email_field :email, class: "form-control" %>
</div>


<div class="form-group">
	<%= f.label :password %>
	<%= f.password_field :password, class: "form-control" %>
</div>

<div class="form-group">
	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation, class: "form_control" %>
</div>

<% f.submit class: "btn btn-primary" %>

<% end %>